name: Flutter CI

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - develop

jobs:
  lint:
    name: Lint & Analyze
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Dart
        uses: dart-lang/setup-dart@v1
        with:
          sdk: stable

      - name: Use FVM and Setup Flutter
        uses: kuhnroyal/flutter-fvm-config-action@v2
        id: fvm-config-action
        with:
          path: ".fvmrc" # .fvmrc ဖိုင်က project မှာ ရှိဖို့လိုတယ်

      - name: Install Flutter SDK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          channel: ${{ steps.fvm-config-action.outputs.FLUTTER_CHANNEL }}
          cache: true
          cache-key: flutter-${{ steps.fvm-config-action.outputs.FLUTTER_VERSION }}
          cache-path: ${{ runner.tool_cache }}/flutter

      - name: Verify Flutter Installation
        run: flutter --version

      - name: Install Dependencies
        run: flutter pub get

      - name: Format Code
        run: dart format --set-exit-if-changed .
        continue-on-error: false # Format မမှန်ရင် fail ဖြစ်အောင်

      - name: Analyze Code
        run: dart analyze --fatal-infos --fatal-warnings .
        continue-on-error: false # Warnings ရှိရင် fail ဖြစ်အောင်

      - name: Run Tests (Optional)
        run: flutter test || echo "No tests found"
        continue-on-error: true # Test မရှိရင် skip လုပ်ဖို့
